#!/bin/bash
#
# This is a command which takes a list of files and
# normalizes certain common unicode symbols.
#
# For instance, it replaces the unicode quotation mark
# with a standard ASCII quotation mark.

native_sed() {
  if [ `uname` == "Darwin" ]; then
    sed -i '' -E "$1" "$2"
  else
    sed -i -e "$1" "$2"
  fi
}

for file in "$@"
do
    echo "$file"

    # Quotes
    native_sed 's/(“|”)/"/g' "$file"
    native_sed "s/(‘|’)/'/g" "$file"

    # En-dash
    native_sed "s/–/--/g" "$file"

    # Em-dash
    native_sed "s/—/--/g" "$file"

    # Ellipsis
    native_sed "s/…/.../g" "$file"

    # No-break space
    native_sed "s/ / /g" "$file"

    # Punctuation space
    native_sed "s/ / /g" "$file"

    # Zero-width space
    native_sed "s/​//g" "$file"
done
